### ISSUE TITLE
Add composer support

### ISSUE THREAD

**Issue by waza-ari** [Sebobo/jquery.smallipop#51]
It would be great if you could add composer support, providing correct requirements and using [component-installer](https://github.com/RobLoach/component-installer) to provide the required JS, CSS and Image files.

Use Case: Many projects use composer, and it is annoying to manage libraries which are used via composer, and manually installed libraries. Thanks!

**Comment by Sebobo** [comment]
I'm a bit tight on time lately and haven't made a non-php package composer compatible yet.
Do you think you could create a pull request for that?
Would be awesome!

**Comment by waza-ari** [comment]
Hi. Sure, no problem. I have created a composer.json file with the required directives to install JS and CSS files to component folder. Hopefully I did not forget anything. Created a pull request for the changes.

**Comment by Sebobo** [comment]
Cool thx :)
I will make a small change but then it's fine.

**Comment by waza-ari** [comment]
Perfect, thank you! And sorry for providing the wrong mail address, was my best guess based on the available information :)

One last thing, though: would you mind to publish the package on [Packagist](https://packagist.org)? This is the default repository for composer users, hence one could avoid adding another repository to composer.json.

**Comment by Sebobo** [comment]
Sure, forgot that. Just added it.

**Comment by waza-ari** [comment]
Package is now available. Thanks!
